version: '3.9'

services:
  say-webface:
    build: '../say_webface'
    env_file: './say-webface.env'
    networks:
      - say-if
    ports:
      - '30000:3000'
    volumes:
      - '../say_webface:/project'  # for development
      - '/project/node_modules/'  # exclude `node_modules` to be binded
    restart: always

  say-wagtail-http:
    build: '../say_wagtail'
    env_file: './say-wagtail.env'
    networks:
      - say-if
    ports:
      - '40001:8000'
    volumes:
    - '../say_wagtail:/project'  # for development
    restart: always
    
  # say-wagtail-grpc:
  #   build: './say_wagtail'
  #   entrypoint: ["python", "manage.py", "grpcserver", "--port", "5061"]
  #   networks:
  #     - say-if
  #   restart: always
    
  say-botel-polling:
    build: '../say_telegram_py'
    env_file: './say-botel.env'
    networks:
      - say-if
    volumes:
      - '../say_botel:/project'  # for development
    restart: 'always'
  
  # say-botel-grpc:
  #   build: './say_botel'
  #   entrypoint: ["python", "main.py" ,"grpc"]
  #   env_file: ./say_botel/.env
  #   networks:
  #     - say-if
  #   restart: always

networks:
  say-if:
