version: '3.9'

services:
  say-webface:
    build: 'sayiforg/say-webface:latest'
    env_file: './say-webface.env'
    networks:
      - say-if
    ports:
      - '30001:3000'
    restart: always

  say-wagtail-http:
    image: 'sayiforg/say-wagtail:latest'
    env_file: './say-wagtail.env'
    networks:
      - say-if
      - pg-main-db
    ports:
      - '40001:8000'
    restart: always
    
  # say-wagtail-grpc:
  #   build: './say_wagtail'
  #   entrypoint: ["python", "manage.py", "grpcserver", "--port", "5061"]
  #   networks:
  #     - say-if
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: always
    
  say-botel-polling:
    image: 'sayiforg/say-botel'
    env_file: './say-botel.env'
    networks:
      - say-if
      - pg-main-db
    restart: 'always'
  
  # say-botel-grpc:
  #   build: './say_botel'
  #   entrypoint: ["python", "main.py" ,"grpc"]
  #   env_file: ./say_botel/.env
  #   networks:
  #     - say-if
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: always
    
  say-keeper:
    image: 'sayiforg/say-keeper'
    env_file: './say-keeper.env'
    ports:
      - '8081:8080'
    networks:
      - say-if
      - pg-main-db
      - redis
    restart: 'always'

networks:
  say-if:
  pg-main-db:
    external: true
  redis:
    external: true
